version: "1.0.{build}"

stack: go 1.11

clone_folder: c:\gopath\src\github.com\capnspacehook\taskmaster

environment:
  GOPATH: c:\gopath
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GOARCH: 386
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GOARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GOARCH: 386
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GOARCH: amd64

platform:
  - x64

build_script:
  - cd c:\gopath\src\github.com\capnspacehook\taskmaster
  - go build -i -v

test_script:
  - cd c:\gopath\src\github.com\capnspacehook\taskmaster
  - go test -cover
